// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ruleId: __t.string().name("rule_id"),
  pattern: __t.string(),
  replacement: __t.string(),
  isActive: __t.bool().name("is_active"),
  isRegex: __t.bool().name("is_regex"),
  sortOrder: __t.u32().name("sort_order"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
