// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.5.0 (commit 19cbf2b219ac9fd7fdca6c5e2c61a3a2f0319515).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import BulkDeleteRequestLogsReducer from "./bulk_delete_request_logs_reducer";
import DeleteAccountReducer from "./delete_account_reducer";
import DeleteApiKeyReducer from "./delete_api_key_reducer";
import DeleteFilterRuleReducer from "./delete_filter_rule_reducer";
import DeleteImageStudioChatReducer from "./delete_image_studio_chat_reducer";
import DeleteModelMappingReducer from "./delete_model_mapping_reducer";
import DeleteProxyReducer from "./delete_proxy_reducer";
import DeleteSettingReducer from "./delete_setting_reducer";
import DeleteUsageSummaryReducer from "./delete_usage_summary_reducer";
import DeleteVccCardReducer from "./delete_vcc_card_reducer";
import InsertImageStudioResultReducer from "./insert_image_studio_result_reducer";
import InsertRequestLogReducer from "./insert_request_log_reducer";
import InsertVccTransactionReducer from "./insert_vcc_transaction_reducer";
import UpdateAccountEnabledReducer from "./update_account_enabled_reducer";
import UpdateAccountQuotaReducer from "./update_account_quota_reducer";
import UpdateAccountStatusReducer from "./update_account_status_reducer";
import UpdateAccountTokensReducer from "./update_account_tokens_reducer";
import UpdateProxyStatsReducer from "./update_proxy_stats_reducer";
import UpdateRequestLogReducer from "./update_request_log_reducer";
import UpsertAccountReducer from "./upsert_account_reducer";
import UpsertApiKeyReducer from "./upsert_api_key_reducer";
import UpsertFilterRuleReducer from "./upsert_filter_rule_reducer";
import UpsertImageStudioChatReducer from "./upsert_image_studio_chat_reducer";
import UpsertModelMappingReducer from "./upsert_model_mapping_reducer";
import UpsertProxyReducer from "./upsert_proxy_reducer";
import UpsertSettingReducer from "./upsert_setting_reducer";
import UpsertUsageSummaryReducer from "./upsert_usage_summary_reducer";
import UpsertVccCardReducer from "./upsert_vcc_card_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AccountsRow from "./accounts_table";
import ApiKeysRow from "./api_keys_table";
import FilterRulesRow from "./filter_rules_table";
import ImageStudioChatsRow from "./image_studio_chats_table";
import ImageStudioResultsRow from "./image_studio_results_table";
import ModelMappingsRow from "./model_mappings_table";
import ProxyPoolRow from "./proxy_pool_table";
import RequestLogsRow from "./request_logs_table";
import SettingsRow from "./settings_table";
import UsageSummaryRow from "./usage_summary_table";
import VccCardsRow from "./vcc_cards_table";
import VccTransactionsRow from "./vcc_transactions_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  accounts: __table({
    name: 'accounts',
    indexes: [
      { accessor: 'id', name: 'accounts_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_provider_email', name: 'accounts_provider_email_idx_btree', algorithm: 'btree', columns: [
        'provider',
        'email',
      ] },
      { accessor: 'by_provider', name: 'accounts_provider_idx_btree', algorithm: 'btree', columns: [
        'provider',
      ] },
    ],
    constraints: [
      { name: 'accounts_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AccountsRow),
  apiKeys: __table({
    name: 'api_keys',
    indexes: [
      { accessor: 'id', name: 'api_keys_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'key', name: 'api_keys_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'api_keys_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'api_keys_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, ApiKeysRow),
  filterRules: __table({
    name: 'filter_rules',
    indexes: [
      { accessor: 'id', name: 'filter_rules_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'ruleId', name: 'filter_rules_rule_id_idx_btree', algorithm: 'btree', columns: [
        'ruleId',
      ] },
    ],
    constraints: [
      { name: 'filter_rules_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'filter_rules_rule_id_key', constraint: 'unique', columns: ['ruleId'] },
    ],
  }, FilterRulesRow),
  imageStudioChats: __table({
    name: 'image_studio_chats',
    indexes: [
      { accessor: 'id', name: 'image_studio_chats_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'image_studio_chats_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ImageStudioChatsRow),
  imageStudioResults: __table({
    name: 'image_studio_results',
    indexes: [
      { accessor: 'by_chat', name: 'image_studio_results_chat_id_idx_btree', algorithm: 'btree', columns: [
        'chatId',
      ] },
      { accessor: 'id', name: 'image_studio_results_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'image_studio_results_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ImageStudioResultsRow),
  modelMappings: __table({
    name: 'model_mappings',
    indexes: [
      { accessor: 'id', name: 'model_mappings_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_priority', name: 'model_mappings_priority_idx_btree', algorithm: 'btree', columns: [
        'priority',
      ] },
    ],
    constraints: [
      { name: 'model_mappings_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ModelMappingsRow),
  proxyPool: __table({
    name: 'proxy_pool',
    indexes: [
      { accessor: 'id', name: 'proxy_pool_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_status', name: 'proxy_pool_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'proxy_pool_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProxyPoolRow),
  requestLogs: __table({
    name: 'request_logs',
    indexes: [
      { accessor: 'by_account', name: 'request_logs_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'by_api_key', name: 'request_logs_api_key_id_idx_btree', algorithm: 'btree', columns: [
        'apiKeyId',
      ] },
      { accessor: 'by_created_at', name: 'request_logs_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'id', name: 'request_logs_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_provider', name: 'request_logs_provider_idx_btree', algorithm: 'btree', columns: [
        'provider',
      ] },
    ],
    constraints: [
      { name: 'request_logs_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RequestLogsRow),
  settings: __table({
    name: 'settings',
    indexes: [
      { accessor: 'key', name: 'settings_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'settings_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, SettingsRow),
  usageSummary: __table({
    name: 'usage_summary',
    indexes: [
      { accessor: 'by_bucket', name: 'usage_summary_bucket_idx_btree', algorithm: 'btree', columns: [
        'bucket',
      ] },
      { accessor: 'by_bucket_provider_model_key', name: 'usage_summary_bucket_provider_model_api_key_id_idx_btree', algorithm: 'btree', columns: [
        'bucket',
        'provider',
        'model',
        'apiKeyId',
      ] },
      { accessor: 'id', name: 'usage_summary_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'usage_summary_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UsageSummaryRow),
  vccCards: __table({
    name: 'vcc_cards',
    indexes: [
      { accessor: 'id', name: 'vcc_cards_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_status', name: 'vcc_cards_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'vcc_cards_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VccCardsRow),
  vccTransactions: __table({
    name: 'vcc_transactions',
    indexes: [
      { accessor: 'by_account', name: 'vcc_transactions_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'id', name: 'vcc_transactions_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'vcc_transactions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VccTransactionsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("bulk_delete_request_logs", BulkDeleteRequestLogsReducer),
  __reducerSchema("delete_account", DeleteAccountReducer),
  __reducerSchema("delete_api_key", DeleteApiKeyReducer),
  __reducerSchema("delete_filter_rule", DeleteFilterRuleReducer),
  __reducerSchema("delete_image_studio_chat", DeleteImageStudioChatReducer),
  __reducerSchema("delete_model_mapping", DeleteModelMappingReducer),
  __reducerSchema("delete_proxy", DeleteProxyReducer),
  __reducerSchema("delete_setting", DeleteSettingReducer),
  __reducerSchema("delete_usage_summary", DeleteUsageSummaryReducer),
  __reducerSchema("delete_vcc_card", DeleteVccCardReducer),
  __reducerSchema("insert_image_studio_result", InsertImageStudioResultReducer),
  __reducerSchema("insert_request_log", InsertRequestLogReducer),
  __reducerSchema("insert_vcc_transaction", InsertVccTransactionReducer),
  __reducerSchema("update_account_enabled", UpdateAccountEnabledReducer),
  __reducerSchema("update_account_quota", UpdateAccountQuotaReducer),
  __reducerSchema("update_account_status", UpdateAccountStatusReducer),
  __reducerSchema("update_account_tokens", UpdateAccountTokensReducer),
  __reducerSchema("update_proxy_stats", UpdateProxyStatsReducer),
  __reducerSchema("update_request_log", UpdateRequestLogReducer),
  __reducerSchema("upsert_account", UpsertAccountReducer),
  __reducerSchema("upsert_api_key", UpsertApiKeyReducer),
  __reducerSchema("upsert_filter_rule", UpsertFilterRuleReducer),
  __reducerSchema("upsert_image_studio_chat", UpsertImageStudioChatReducer),
  __reducerSchema("upsert_model_mapping", UpsertModelMappingReducer),
  __reducerSchema("upsert_proxy", UpsertProxyReducer),
  __reducerSchema("upsert_setting", UpsertSettingReducer),
  __reducerSchema("upsert_usage_summary", UpsertUsageSummaryReducer),
  __reducerSchema("upsert_vcc_card", UpsertVccCardReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.5.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

