// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  accountId: __t.option(__t.u64()),
  provider: __t.string(),
  model: __t.option(__t.string()),
  promptTokens: __t.u64(),
  completionTokens: __t.u64(),
  totalTokens: __t.u64(),
  creditsUsed: __t.f64(),
  status: __t.string(),
  durationMs: __t.option(__t.u64()),
  errorMessage: __t.option(__t.string()),
  requestBody: __t.option(__t.string()),
  responseBody: __t.option(__t.string()),
  accountEmail: __t.option(__t.string()),
  accountQuotaBefore: __t.f64(),
  accountQuotaAfter: __t.f64(),
  apiKeyId: __t.option(__t.u64()),
  apiKeyName: __t.option(__t.string()),
  compressionStats: __t.option(__t.string()),
};
