// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  accountId: __t.option(__t.u64()),
  cardLast4: __t.string(),
  cardBrand: __t.option(__t.string()),
  amount: __t.option(__t.f64()),
  currency: __t.string(),
  status: __t.string(),
  stripeChargeId: __t.option(__t.string()),
};
