// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  url: __t.string(),
  proxyType: __t.string().name("proxy_type"),
  label: __t.option(__t.string()),
  status: __t.string(),
  lastUsedAt: __t.option(__t.u64()).name("last_used_at"),
  lastCheckedAt: __t.option(__t.u64()).name("last_checked_at"),
  errorMessage: __t.option(__t.string()).name("error_message"),
  latencyMs: __t.option(__t.u64()).name("latency_ms"),
  successCount: __t.u64().name("success_count"),
  failCount: __t.u64().name("fail_count"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
