// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  accountId: __t.option(__t.u64()).name("account_id"),
  provider: __t.string(),
  model: __t.option(__t.string()),
  promptTokens: __t.u64().name("prompt_tokens"),
  completionTokens: __t.u64().name("completion_tokens"),
  totalTokens: __t.u64().name("total_tokens"),
  creditsUsed: __t.f64().name("credits_used"),
  status: __t.string(),
  durationMs: __t.option(__t.u64()).name("duration_ms"),
  errorMessage: __t.option(__t.string()).name("error_message"),
  requestBody: __t.option(__t.string()).name("request_body"),
  responseBody: __t.option(__t.string()).name("response_body"),
  accountEmail: __t.option(__t.string()).name("account_email"),
  accountQuotaBefore: __t.f64().name("account_quota_before"),
  accountQuotaAfter: __t.f64().name("account_quota_after"),
  apiKeyId: __t.option(__t.u64()).name("api_key_id"),
  apiKeyName: __t.option(__t.string()).name("api_key_name"),
  createdAt: __t.u64().name("created_at"),
  compressionStats: __t.option(__t.string()).name("compression_stats"),
});
