// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Accounts = __t.object("Accounts", {
  id: __t.u64(),
  provider: __t.string(),
  email: __t.string(),
  password: __t.string(),
  status: __t.string(),
  enabled: __t.bool(),
  tokens: __t.option(__t.string()),
  quotaLimit: __t.f64(),
  quotaRemaining: __t.f64(),
  quotaResetAt: __t.option(__t.u64()),
  lastUsedAt: __t.option(__t.u64()),
  lastLoginAt: __t.option(__t.u64()),
  errorMessage: __t.option(__t.string()),
  metadata: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Accounts = __Infer<typeof Accounts>;

export const ApiKeys = __t.object("ApiKeys", {
  id: __t.u64(),
  name: __t.string(),
  key: __t.string(),
  createdAt: __t.u64(),
});
export type ApiKeys = __Infer<typeof ApiKeys>;

export const FilterRules = __t.object("FilterRules", {
  id: __t.u64(),
  ruleId: __t.string(),
  pattern: __t.string(),
  replacement: __t.string(),
  isActive: __t.bool(),
  isRegex: __t.bool(),
  sortOrder: __t.u32(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type FilterRules = __Infer<typeof FilterRules>;

export const ImageStudioChats = __t.object("ImageStudioChats", {
  id: __t.u64(),
  title: __t.option(__t.string()),
  messages: __t.string(),
  finalPrompt: __t.option(__t.string()),
  options: __t.string(),
  assistModel: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type ImageStudioChats = __Infer<typeof ImageStudioChats>;

export const ImageStudioResults = __t.object("ImageStudioResults", {
  id: __t.u64(),
  chatId: __t.option(__t.u64()),
  prompt: __t.string(),
  resultType: __t.string(),
  aspectRatio: __t.string(),
  n: __t.u32(),
  urls: __t.string(),
  creditsUsed: __t.f64(),
  createdAt: __t.u64(),
});
export type ImageStudioResults = __Infer<typeof ImageStudioResults>;

export const ModelMappings = __t.object("ModelMappings", {
  id: __t.u64(),
  sourcePattern: __t.string(),
  matchType: __t.string(),
  targetModel: __t.string(),
  enabled: __t.bool(),
  priority: __t.u32(),
  label: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type ModelMappings = __Infer<typeof ModelMappings>;

export const ProxyPool = __t.object("ProxyPool", {
  id: __t.u64(),
  url: __t.string(),
  proxyType: __t.string(),
  label: __t.option(__t.string()),
  status: __t.string(),
  lastUsedAt: __t.option(__t.u64()),
  lastCheckedAt: __t.option(__t.u64()),
  errorMessage: __t.option(__t.string()),
  latencyMs: __t.option(__t.u64()),
  successCount: __t.u64(),
  failCount: __t.u64(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type ProxyPool = __Infer<typeof ProxyPool>;

export const RequestLogs = __t.object("RequestLogs", {
  id: __t.u64(),
  accountId: __t.option(__t.u64()),
  provider: __t.string(),
  model: __t.option(__t.string()),
  promptTokens: __t.u64(),
  completionTokens: __t.u64(),
  totalTokens: __t.u64(),
  creditsUsed: __t.f64(),
  status: __t.string(),
  durationMs: __t.option(__t.u64()),
  errorMessage: __t.option(__t.string()),
  requestBody: __t.option(__t.string()),
  responseBody: __t.option(__t.string()),
  accountEmail: __t.option(__t.string()),
  accountQuotaBefore: __t.f64(),
  accountQuotaAfter: __t.f64(),
  apiKeyId: __t.option(__t.u64()),
  apiKeyName: __t.option(__t.string()),
  createdAt: __t.u64(),
  compressionStats: __t.option(__t.string()),
});
export type RequestLogs = __Infer<typeof RequestLogs>;

export const Settings = __t.object("Settings", {
  key: __t.string(),
  value: __t.option(__t.string()),
  updatedAt: __t.u64(),
});
export type Settings = __Infer<typeof Settings>;

export const UsageSummary = __t.object("UsageSummary", {
  id: __t.u64(),
  bucket: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  apiKeyId: __t.u64(),
  apiKeyName: __t.option(__t.string()),
  totalRequests: __t.u64(),
  successRequests: __t.u64(),
  errorRequests: __t.u64(),
  promptTokens: __t.u64(),
  completionTokens: __t.u64(),
  totalTokens: __t.u64(),
  creditsUsed: __t.f64(),
  totalDurationMs: __t.u64(),
});
export type UsageSummary = __Infer<typeof UsageSummary>;

export const VccCards = __t.object("VccCards", {
  id: __t.u64(),
  number: __t.string(),
  expMonth: __t.string(),
  expYear: __t.string(),
  cvv: __t.string(),
  name: __t.string(),
  status: __t.string(),
  usedByAccountId: __t.option(__t.u64()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type VccCards = __Infer<typeof VccCards>;

export const VccTransactions = __t.object("VccTransactions", {
  id: __t.u64(),
  accountId: __t.option(__t.u64()),
  cardLast4: __t.string(),
  cardBrand: __t.option(__t.string()),
  amount: __t.option(__t.f64()),
  currency: __t.string(),
  status: __t.string(),
  stripeChargeId: __t.option(__t.string()),
  createdAt: __t.u64(),
});
export type VccTransactions = __Infer<typeof VccTransactions>;

