// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.u64(),
  promptTokens: __t.u64(),
  completionTokens: __t.u64(),
  totalTokens: __t.u64(),
  creditsUsed: __t.f64(),
  status: __t.string(),
  durationMs: __t.option(__t.u64()),
  errorMessage: __t.option(__t.string()),
  accountQuotaAfter: __t.f64(),
};
