// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.u64(),
  successCount: __t.u64(),
  failCount: __t.u64(),
  lastUsedAt: __t.option(__t.u64()),
  lastCheckedAt: __t.option(__t.u64()),
  latencyMs: __t.option(__t.u64()),
  status: __t.string(),
  errorMessage: __t.option(__t.string()),
};
