// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  bucket: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  apiKeyId: __t.u64(),
  apiKeyName: __t.option(__t.string()),
  totalRequests: __t.u64(),
  successRequests: __t.u64(),
  errorRequests: __t.u64(),
  promptTokens: __t.u64(),
  completionTokens: __t.u64(),
  totalTokens: __t.u64(),
  creditsUsed: __t.f64(),
  totalDurationMs: __t.u64(),
};
