// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.u64(),
  provider: __t.string(),
  email: __t.string(),
  password: __t.string(),
  status: __t.string(),
  enabled: __t.bool(),
  tokens: __t.option(__t.string()),
  quotaLimit: __t.f64(),
  quotaRemaining: __t.f64(),
  quotaResetAt: __t.option(__t.u64()),
  lastUsedAt: __t.option(__t.u64()),
  lastLoginAt: __t.option(__t.u64()),
  errorMessage: __t.option(__t.string()),
  metadata: __t.option(__t.string()),
};
