// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  bucket: __t.string(),
  provider: __t.string(),
  model: __t.string(),
  apiKeyId: __t.u64().name("api_key_id"),
  apiKeyName: __t.option(__t.string()).name("api_key_name"),
  totalRequests: __t.u64().name("total_requests"),
  successRequests: __t.u64().name("success_requests"),
  errorRequests: __t.u64().name("error_requests"),
  promptTokens: __t.u64().name("prompt_tokens"),
  completionTokens: __t.u64().name("completion_tokens"),
  totalTokens: __t.u64().name("total_tokens"),
  creditsUsed: __t.f64().name("credits_used"),
  totalDurationMs: __t.u64().name("total_duration_ms"),
});
