// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  accountId: __t.option(__t.u64()).name("account_id"),
  cardLast4: __t.string().name("card_last_4"),
  cardBrand: __t.option(__t.string()).name("card_brand"),
  amount: __t.option(__t.f64()),
  currency: __t.string(),
  status: __t.string(),
  stripeChargeId: __t.option(__t.string()).name("stripe_charge_id"),
  createdAt: __t.u64().name("created_at"),
});
