// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BulkDeleteRequestLogsReducer from "../bulk_delete_request_logs_reducer";
import DeleteAccountReducer from "../delete_account_reducer";
import DeleteApiKeyReducer from "../delete_api_key_reducer";
import DeleteFilterRuleReducer from "../delete_filter_rule_reducer";
import DeleteImageStudioChatReducer from "../delete_image_studio_chat_reducer";
import DeleteModelMappingReducer from "../delete_model_mapping_reducer";
import DeleteProxyReducer from "../delete_proxy_reducer";
import DeleteSettingReducer from "../delete_setting_reducer";
import DeleteVccCardReducer from "../delete_vcc_card_reducer";
import InsertImageStudioResultReducer from "../insert_image_studio_result_reducer";
import InsertRequestLogReducer from "../insert_request_log_reducer";
import InsertVccTransactionReducer from "../insert_vcc_transaction_reducer";
import UpdateAccountEnabledReducer from "../update_account_enabled_reducer";
import UpdateAccountQuotaReducer from "../update_account_quota_reducer";
import UpdateAccountStatusReducer from "../update_account_status_reducer";
import UpdateAccountTokensReducer from "../update_account_tokens_reducer";
import UpdateProxyStatsReducer from "../update_proxy_stats_reducer";
import UpdateRequestLogReducer from "../update_request_log_reducer";
import UpsertAccountReducer from "../upsert_account_reducer";
import UpsertApiKeyReducer from "../upsert_api_key_reducer";
import UpsertFilterRuleReducer from "../upsert_filter_rule_reducer";
import UpsertImageStudioChatReducer from "../upsert_image_studio_chat_reducer";
import UpsertModelMappingReducer from "../upsert_model_mapping_reducer";
import UpsertProxyReducer from "../upsert_proxy_reducer";
import UpsertSettingReducer from "../upsert_setting_reducer";
import UpsertUsageSummaryReducer from "../upsert_usage_summary_reducer";
import UpsertVccCardReducer from "../upsert_vcc_card_reducer";

export type BulkDeleteRequestLogsParams = __Infer<typeof BulkDeleteRequestLogsReducer>;
export type DeleteAccountParams = __Infer<typeof DeleteAccountReducer>;
export type DeleteApiKeyParams = __Infer<typeof DeleteApiKeyReducer>;
export type DeleteFilterRuleParams = __Infer<typeof DeleteFilterRuleReducer>;
export type DeleteImageStudioChatParams = __Infer<typeof DeleteImageStudioChatReducer>;
export type DeleteModelMappingParams = __Infer<typeof DeleteModelMappingReducer>;
export type DeleteProxyParams = __Infer<typeof DeleteProxyReducer>;
export type DeleteSettingParams = __Infer<typeof DeleteSettingReducer>;
export type DeleteVccCardParams = __Infer<typeof DeleteVccCardReducer>;
export type InsertImageStudioResultParams = __Infer<typeof InsertImageStudioResultReducer>;
export type InsertRequestLogParams = __Infer<typeof InsertRequestLogReducer>;
export type InsertVccTransactionParams = __Infer<typeof InsertVccTransactionReducer>;
export type UpdateAccountEnabledParams = __Infer<typeof UpdateAccountEnabledReducer>;
export type UpdateAccountQuotaParams = __Infer<typeof UpdateAccountQuotaReducer>;
export type UpdateAccountStatusParams = __Infer<typeof UpdateAccountStatusReducer>;
export type UpdateAccountTokensParams = __Infer<typeof UpdateAccountTokensReducer>;
export type UpdateProxyStatsParams = __Infer<typeof UpdateProxyStatsReducer>;
export type UpdateRequestLogParams = __Infer<typeof UpdateRequestLogReducer>;
export type UpsertAccountParams = __Infer<typeof UpsertAccountReducer>;
export type UpsertApiKeyParams = __Infer<typeof UpsertApiKeyReducer>;
export type UpsertFilterRuleParams = __Infer<typeof UpsertFilterRuleReducer>;
export type UpsertImageStudioChatParams = __Infer<typeof UpsertImageStudioChatReducer>;
export type UpsertModelMappingParams = __Infer<typeof UpsertModelMappingReducer>;
export type UpsertProxyParams = __Infer<typeof UpsertProxyReducer>;
export type UpsertSettingParams = __Infer<typeof UpsertSettingReducer>;
export type UpsertUsageSummaryParams = __Infer<typeof UpsertUsageSummaryReducer>;
export type UpsertVccCardParams = __Infer<typeof UpsertVccCardReducer>;

